# App name
spring.application.name=taskmanager

# ================= DATABASE =================

# Railway PostgreSQL (production)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/taskmanager?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:renuka123}

# Driver auto-switch (IMPORTANT)
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= PORT =================
server.port=${PORT:8080}